# Generated by Django 5.2.17 on 2026-10-08 10:45

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_sla_policies_and_backfill_tickets(apps, schema_editor):
    database = schema_editor.connection.alias
    sla_policy_model = apps.get_model('tickets', 'SlaPolicy')
    ticket_model = apps.get_model('tickets', 'Ticket')
    policy_targets = {
        'CRITICAL': (timedelta(minutes=15), timedelta(hours=4)),
        'HIGH': (timedelta(minutes=30), timedelta(hours=8)),
        'MEDIUM': (timedelta(hours=2), timedelta(hours=24)),
        'LOW': (timedelta(hours=4), timedelta(hours=72)),
    }
    policies = {}
    for priority, (response_target, resolution_target) in policy_targets.items():
        policies[priority], _ = sla_policy_model.objects.using(database).get_or_create(
            priority=priority,
            defaults={
                'response_target': response_target,
                'resolution_target': resolution_target,
            },
        )

    current_time = timezone.now()
    for ticket in ticket_model.objects.using(database).filter(sla_policy__isnull=True).iterator():
        policy = policies[ticket.priority]
        first_response_due_at = ticket.created_at + policy.response_target
        resolution_due_at = ticket.created_at + policy.resolution_target
        ticket.sla_policy = policy
        ticket.first_response_due_at = first_response_due_at
        ticket.resolution_due_at = resolution_due_at
        ticket.response_breached = (
            ticket.first_responded_at > first_response_due_at
            if ticket.first_responded_at
            else current_time >= first_response_due_at
        )
        ticket.resolution_breached = (
            ticket.resolved_at > resolution_due_at
            if ticket.resolved_at
            else current_time >= resolution_due_at
        )
        ticket.save(
            using=database,
            update_fields=(
                'sla_policy',
                'first_response_due_at',
                'resolution_due_at',
                'response_breached',
                'resolution_breached',
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_at_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, unique=True)),
                ('response_target', models.DurationField()),
                ('resolution_target', models.DurationField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('PENDED', 'Set Pending'), ('RESUMED', 'Resumed'), ('FIRST_RESPONSE', 'First Response'), ('SLA_WARNING', 'SLA Warning'), ('SLA_BREACHED', 'SLA Breached'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.slapolicy'),
        ),
        migrations.RunPython(
            seed_sla_policies_and_backfill_tickets,
            migrations.RunPython.noop,
        ),
    ]
